# Generated by Django 4.0.4 on 2022-06-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Awardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
