# Generated by Django 4.0.4 on 2022-06-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Awardapp', '0002_profile_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
