# Generated by Django 3.2 on 2022-06-15 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Awardapp', '0005_remove_rating_average_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='average_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
